#!/bin/bash
# Create Orange Pi deployment package (.tgz)
#
# Orange Pi runs Armbian / Debian / Ubuntu and has no piCorePlayer variant, so
# this package skips the TinyCore branch of the Raspberry Pi installer and
# instead helps the user find the right I2C bus, SPI node and GPIO controller,
# none of which match the Pi's conventions.
#
# One aarch64 package covers both the Rockchip boards (RK3588/RK3566/RK3399) and
# the 64-bit Allwinner ones (H618).  They differ in GPIO line numbering, which
# is a config matter; see the README inside the package.
#
# Every display driver ships in the package regardless of board: ssd1306,
# ssd1309, sh1106 and sh1107 on I2C or SPI, and ssd1322, sh1122, st7789,
# st7796s and sharpmemory on SPI.  The panel is chosen at runtime in
# lymons.yaml, not at build time.

set -e

TARGET="${1:-aarch64-unknown-linux-gnu}"
VERSION=$(grep '^version' Cargo.toml | head -1 | sed 's/.*"\(.*\)".*/\1/')
ARCH=$(echo "${TARGET}" | cut -d'-' -f1)
PACKAGE_NAME="lymons-${VERSION}-opi-${ARCH}"
BUILD_DIR="/tmp/${PACKAGE_NAME}"

case "${TARGET}" in
    aarch64-*) STRIP_TOOL="aarch64-linux-gnu-strip" ;;
    *)         STRIP_TOOL="strip" ;;
esac

echo "Creating Orange Pi deployment package..."
echo "Version: ${VERSION}"
echo "Target:  ${TARGET}"
echo "Arch:    ${ARCH}"

# Verify cross-compiled binary exists
if [ ! -f "target/${TARGET}/release/LyMonS" ]; then
    echo "Error: Cross-compiled binary not found!"
    echo "Please run: ./scripts/cross-compile-opi.sh ${TARGET} first"
    exit 1
fi

# Clean and create flat build structure
rm -rf "${BUILD_DIR}"
mkdir -p "${BUILD_DIR}"/{bin,drivers,data,assets,fonts,config}

# Copy binary
echo "Copying binary..."
cp "target/${TARGET}/release/LyMonS" "${BUILD_DIR}/bin/"
${STRIP_TOOL} "${BUILD_DIR}/bin/LyMonS" 2>/dev/null || echo "Strip failed (non-fatal)"

# Copy runtime assets and resources
echo "Copying runtime assets and resources..."
cp -fr assets/. "${BUILD_DIR}/assets/"
cp -fr data/.   "${BUILD_DIR}/data/"
cp -fr fonts/.  "${BUILD_DIR}/fonts/"

# Copy plugins
echo "Copying plugins..."
if ls target/${TARGET}/release/drivers/liblymons_driver_*.so 1>/dev/null 2>&1; then
    cp target/${TARGET}/release/drivers/liblymons_driver_*.so "${BUILD_DIR}/drivers/"
    ${STRIP_TOOL} "${BUILD_DIR}/drivers/"*.so 2>/dev/null || echo "Strip plugins failed (non-fatal)"
else
    echo "Warning: No plugin drivers found in target/${TARGET}/release/drivers/"
fi

# Config template. The driver folder path is set by install.sh at deploy time.
cat > "${BUILD_DIR}/config/lymons.yaml.example" <<'EOF'
# LyMonS Configuration for Orange Pi
# Generated by install.sh. Review and edit before running.
#
# The bus paths below are Orange Pi defaults, NOT Raspberry Pi ones.  Run
# ./show-buses.sh (shipped with this package) to see what your board exposes.

display:
  folder: /DRIVER_DIR/      # set automatically by installer
  # Options: ssd1306, ssd1309, sh1106, sh1107, ssd1322, sh1122,
  #          st7789, st7796s, sharpmemory
  driver: sh1107

  # Only needed for drivers offering more than one panel size (sh1107, st7789).
  # Single-size drivers ignore these. See the Supported Displays table in
  # README.md for the sizes each driver accepts.
  width: 128
  height: 128

  # --- I2C: ssd1306, ssd1309, sh1106, sh1107 --------------------------------
  # The bus number varies by board. The Orange Pi 5 family commonly exposes
  # i2c5 on header pins 3/5, the 3B i2c3, the Zero 3 i2c3.  Enable the overlay in
  # /boot/armbianEnv.txt first, then run ./show-buses.sh to see what appeared.
  bus:
    type: i2c
    bus: "/dev/i2c-5"
    address: 0x3C           # Common: 0x3C or 0x3D

  # --- SPI: any driver above, plus ssd1322, sh1122, st7789, st7796s and
  #          sharpmemory, which are SPI only ---------------------------------
  # Replace the i2c block above with this to drive a 4-wire SPI panel.
  #
  # gpio_chip names the GPIO controller carrying DC/RST.  Unlike a Pi there is
  # no single header chip and no global pin numbering:
  #
  #   Rockchip (OPi 5 / 3B / 4)  one controller per bank, gpio0 through gpio4:
  #     line = group * 8 + index      (group A=0, B=1, C=2, D=3)
  #     PC7  = 2 * 8 + 7 = 23         ->  gpio_chip: gpio3, pin 23
  #
  #   Allwinner (OPi Zero 3 / Zero 2W)  main pinctrl + R_PIO for the PL bank:
  #     line = bank * 32 + index      (bank A=0, B=1, C=2 ... I=8)
  #     PC7  = 2 * 32 + 7 = 71        ->  gpio_chip: 300b000.pinctrl, pin 71
  #
  # ./show-buses.sh prints the controller labels your board actually has.
  #
  # bus:
  #   type: spi
  #   bus: "/dev/spidev4.0"
  #   gpio_chip: "gpio3"    # or "/dev/gpiochip3", or "3"
  #   dc_pin: 23            # bank-relative line, NOT a BCM number
  #   rst_pin: 24
  #   speed_hz: 8000000

  brightness: 128           # 0-255
  rotate_deg: 0             # 0, 90, 180, 270
  invert: false

# Location, used for sunrise/sunset and moon calculations
# Find your coordinates at https://www.latlong.net/
latitude: 42.36141
longitude: -71.10407

# Slim Server Connection (auto-detected if not specified)
# slimserver:
#   host: "localhost"
#   port: 9000

# Player MAC Address (auto-detected if not specified)
# player_mac: "aa:bb:cc:dd:ee:ff"
EOF

# Bus discovery helper, the single most useful thing on an unfamiliar board.
# Shared with the Raspberry Pi packages; it detects the board family at runtime
# and prints the numbering rules that apply.
if [ ! -f scripts/show-buses.sh ]; then
    echo "Error: scripts/show-buses.sh not found (run this from the repo root)"
    exit 1
fi
cp scripts/show-buses.sh "${BUILD_DIR}/show-buses.sh"
chmod +x "${BUILD_DIR}/show-buses.sh"

# Installer, Armbian / Debian / Ubuntu only
cat > "${BUILD_DIR}/install.sh" <<'INSTALLEOF'
#!/bin/sh
# LyMonS Orange Pi Installer (Armbian / Debian / Ubuntu)

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "LyMonS Installer for Orange Pi"
echo "============================"

RUNTIME_DIR="${HOME}/lymons"
BIN_DIR="/usr/local/bin"
DRIVER_DIR="/usr/local/lib/lymons/drivers"
CONFIG_DIR="${RUNTIME_DIR}/config"

echo ""
echo "  Runtime : ${RUNTIME_DIR}"
echo "  Binary  : ${BIN_DIR}/LyMonS"
echo "  Drivers : ${DRIVER_DIR}"
echo "  Config  : ${CONFIG_DIR}/lymons.yaml"
echo ""

mkdir -p "${RUNTIME_DIR}/data" "${RUNTIME_DIR}/assets" "${RUNTIME_DIR}/fonts" \
         "${CONFIG_DIR}" "${DRIVER_DIR}" "${BIN_DIR}"

# Deploy binary
cp "${SCRIPT_DIR}/bin/LyMonS" "${BIN_DIR}/LyMonS"
chmod +x "${BIN_DIR}/LyMonS"
echo "Installed binary: ${BIN_DIR}/LyMonS"

# Deploy drivers
if ls "${SCRIPT_DIR}/drivers/"*.so 1>/dev/null 2>&1; then
    cp "${SCRIPT_DIR}/drivers/"*.so "${DRIVER_DIR}/"
    echo "Installed drivers to ${DRIVER_DIR}/"
else
    echo "Warning: No driver plugins found in package"
fi

# Deploy runtime resources
cp -rf "${SCRIPT_DIR}/data/."   "${RUNTIME_DIR}/data/"
cp -rf "${SCRIPT_DIR}/assets/." "${RUNTIME_DIR}/assets/"
cp -rf "${SCRIPT_DIR}/fonts/."  "${RUNTIME_DIR}/fonts/"
cp -f  "${SCRIPT_DIR}/show-buses.sh" "${RUNTIME_DIR}/show-buses.sh"
chmod +x "${RUNTIME_DIR}/show-buses.sh"
echo "Installed runtime resources to ${RUNTIME_DIR}/"

# Deploy config: create from example if not already present, patch driver path
if [ ! -f "${CONFIG_DIR}/lymons.yaml" ]; then
    sed "s|folder: /DRIVER_DIR/|folder: ${DRIVER_DIR}/|" \
        "${SCRIPT_DIR}/config/lymons.yaml.example" > "${CONFIG_DIR}/lymons.yaml"
    echo "Created ${CONFIG_DIR}/lymons.yaml, set your display bus and location"
else
    echo "Config exists, leaving ${CONFIG_DIR}/lymons.yaml unchanged"
fi

# Launch script
cat > "${RUNTIME_DIR}/gomonitor" <<GOEOF
#!/bin/sh
# LyMonS for Orange Pi - it's worth the squeeze
RUNTIME_DIR="${RUNTIME_DIR}"

# Stop any running instance
killall LyMonS > /dev/null 2>&1; sleep 1
killall -9 LyMonS > /dev/null 2>&1

# Wait for squeezelite (up to 30s), skip if not found
WAIT=0
while [ \$WAIT -lt 30 ]; do
    pidof squeezelite squeezelite-dsd > /dev/null 2>&1 && break
    sleep 1
    WAIT=\$((WAIT + 1))
done

cd "\${RUNTIME_DIR}"
exec sudo LyMonS \
    --config="${CONFIG_DIR}/lymons.yaml" \
    "\$@" > /dev/null 2>&1 &
GOEOF
chmod +x "${RUNTIME_DIR}/gomonitor"
echo "Generated ${RUNTIME_DIR}/gomonitor"

# Make sure the character devices are reachable
modprobe i2c-dev > /dev/null 2>&1
for grp in i2c spi gpio; do
    getent group "${grp}" > /dev/null 2>&1 && adduser "${SUDO_USER:-$USER}" "${grp}" > /dev/null 2>&1
done

echo ""
echo "Installation complete!"
echo ""
echo "  1. Enable the buses you need in /boot/armbianEnv.txt, e.g.:"
echo "       overlays=i2c5-m3 spi4-m0-cs1-spidev"
echo "     (armbian-config > System > Hardware lists the overlays for your board)"
echo "     then reboot."
echo "  2. See what the board exposes : ${RUNTIME_DIR}/show-buses.sh"
echo "  3. Edit config                : ${CONFIG_DIR}/lymons.yaml"
echo "  4. Test                       : ${RUNTIME_DIR}/gomonitor"
echo "  5. Autostart                  : add to /etc/rc.local before 'exit 0':"
echo "                                  ${RUNTIME_DIR}/gomonitor &"
INSTALLEOF
chmod +x "${BUILD_DIR}/install.sh"

# Package README
cat > "${BUILD_DIR}/README.md" <<EOF
# LyMonS ${VERSION} for Orange Pi (${ARCH})

Dynamic OLED display driver for Lyrion Media Server.

Built for the current 64-bit Orange Pi boards, Rockchip and Allwinner alike,
running Armbian, Debian or Ubuntu:

| Board                                           | SoC              | GPIO layout |
|-------------------------------------------------|------------------|-------------|
| Orange Pi 5 / 5B / 5 Plus / 5 Pro / 5 Max / CM5 | RK3588 / RK3588S | Rockchip    |
| Orange Pi 3B                                    | RK3566           | Rockchip    |
| Orange Pi 4 / 4 LTS                             | RK3399           | Rockchip    |
| Orange Pi Zero 3 / Zero 2W                      | Allwinner H618   | Allwinner   |

Only the older 32-bit Allwinner boards (Zero / Zero LTS on H2+/H3, PC, PC Plus,
One) fall outside this package. They run the \`armv7\` Raspberry Pi package
instead: the binary is architecture-compatible, and only the bus and GPIO
configuration differs, exactly as described below.

## Installation

\`\`\`bash
tar xzf ${PACKAGE_NAME}.tgz
cd ${PACKAGE_NAME}
sudo ./install.sh
\`\`\`

## Board setup (do this first)

Orange Pi does not use \`raspi-config\` or \`/boot/config.txt\`.  Enable the I2C or
SPI overlay for your board in \`/boot/armbianEnv.txt\`. Under \`armbian-config\`,
System then Hardware lists what is available. Reboot afterwards:

\`\`\`
overlays=i2c5-m3 spi4-m0-cs1-spidev
\`\`\`

Then run \`./show-buses.sh\` to see the resulting \`/dev/i2c-*\`, \`/dev/spidev*\`
and GPIO controllers, and put those into \`lymons.yaml\`.

## GPIO pins are not BCM numbers

On a Raspberry Pi the whole 40-pin header is one GPIO controller whose line
offsets happen to be the BCM numbers, so \`dc_pin: 24\` means BCM 24.

**Rockchip** registers one controller per bank, \`gpio0\` through \`gpio4\` with 32
lines each, so you must name the bank and give a bank-relative line:

\`\`\`
line = group * 8 + index        (group A=0, B=1, C=2, D=3)
PC7  = 2 * 8 + 7 = 23           on bank 3
\`\`\`

**Allwinner** (Zero 3 / Zero 2W) uses two controllers instead, the main pinctrl
and the R_PIO that carries the PL bank, with a flat number inside each:

\`\`\`
line = bank * 32 + index        (bank A=0, B=1, C=2 ... I=8)
PC7  = 2 * 32 + 7 = 71          on the main pinctrl
PL10 = 10                       on the R_PIO controller
\`\`\`

Run \`./show-buses.sh\` for the exact controller labels on your board. They are
device-tree node names such as \`gpio3\` (Rockchip) or \`300b000.pinctrl\`
(Allwinner), and \`gpio_chip\` accepts either the label or the \`/dev/gpiochipN\`
path.

\`\`\`yaml
bus:
  type: spi
  bus: "/dev/spidev4.0"
  gpio_chip: "gpio3"    # bank, also accepts "/dev/gpiochip3" or "3"
  dc_pin: 23            # bank-relative line
  rst_pin: 24
\`\`\`

Plugin drivers do not read the YAML config; set \`LYMONS_GPIO_CHIP=gpio3\` in the
environment for those.

## Supported Displays

Color depth is a property of the driver, not the panel size.

| Driver        | Bus     | Color depth    | Panel sizes                                         |
|---------------|---------|----------------|-----------------------------------------------------|
| \`ssd1306\`     | I2C/SPI | Mono (1bpp)    | 128x64                                              |
| \`ssd1309\`     | I2C/SPI | Mono (1bpp)    | 128x64                                              |
| \`sh1106\`      | I2C/SPI | Mono (1bpp)    | 132x64                                              |
| \`sh1107\`      | I2C/SPI | Mono (1bpp)    | 128x128, 128x64                                     |
| \`ssd1322\`     | SPI     | Gray4 (4bpp)   | 256x64                                              |
| \`sh1122\`      | SPI     | Gray4 (4bpp)   | 256x64                                              |
| \`st7789\`      | SPI     | Rgb565 (16bpp) | 320x240, 320x170, 280x240, 240x240, 240x135, 160x80 |
| \`st7796s\`     | SPI     | Rgb565 (16bpp) | 480x320                                             |
| \`sharpmemory\` | SPI     | Mono (1bpp)    | 400x240                                             |

Set \`width\` and \`height\` in the \`display:\` block for the drivers that offer more
than one panel size. The rest fix their own size and ignore the values.

I2C panels need only \`bus\` and \`address\`. SPI panels additionally need \`dc_pin\`,
usually \`rst_pin\`, and on this board family \`gpio_chip\` as described above.

## Autostart

Add to \`/etc/rc.local\` before \`exit 0\`:
\`\`\`bash
\${HOME}/lymons/gomonitor &
\`\`\`

## License

GPL-3.0-or-later. Version ${VERSION} ($(date +%Y-%m-%d)). Built for: ${TARGET}
EOF

# Create package
cd /tmp
echo "Creating tarball..."
tar czf "${PACKAGE_NAME}.tgz" "${PACKAGE_NAME}/"
mv "${PACKAGE_NAME}.tgz" "${OLDPWD}/"

BINARY_SIZE=$(du -h "${BUILD_DIR}/bin/LyMonS" | cut -f1)
PACKAGE_SIZE=$(du -h "${OLDPWD}/${PACKAGE_NAME}.tgz" | cut -f1)

echo ""
echo "✓ Package created: ${PACKAGE_NAME}.tgz"
echo "  Binary:  ${BINARY_SIZE}"
echo "  Package: ${PACKAGE_SIZE}"
echo ""
echo "To deploy:"
echo "  tar xzf ${PACKAGE_NAME}.tgz && cd ${PACKAGE_NAME} && sudo ./install.sh"
