#!/bin/bash
# Create universal Raspberry Pi deployment package (.tgz)
# Single package works on piCorePlayer (TinyCore) and standard Raspberry Pi Linux
# install.sh detects the environment and deploys accordingly

set -e

TARGET="${1:-armv7-unknown-linux-gnueabihf}"
VERSION=$(grep '^version' Cargo.toml | head -1 | sed 's/.*"\(.*\)".*/\1/')
ARCH=$(echo "${TARGET}" | cut -d'-' -f1)
# The ARMv6 target triple is "arm-*"; present it to users as "armv6"
[ "${ARCH}" = "arm" ] && ARCH="armv6"
PACKAGE_NAME="lymons-${VERSION}-pcp-${ARCH}"
BUILD_DIR="/tmp/${PACKAGE_NAME}"

case "${TARGET}" in
    arm-*|armv7-*) STRIP_TOOL="arm-linux-gnueabihf-strip" ;;
    aarch64-*)     STRIP_TOOL="aarch64-linux-gnu-strip" ;;
    *)             STRIP_TOOL="strip" ;;
esac

echo "Creating universal deployment package..."
echo "Version: ${VERSION}"
echo "Target:  ${TARGET}"
echo "Arch:    ${ARCH}"

# Verify cross-compiled binary exists
if [ ! -f "target/${TARGET}/release/LyMonS" ]; then
    echo "Error: Cross-compiled binary not found!"
    echo "Please run: ./scripts/cross-compile-pi.sh ${TARGET} first"
    exit 1
fi

# Clean and create flat build structure
rm -rf "${BUILD_DIR}"
mkdir -p "${BUILD_DIR}"/{bin,drivers,data,assets,fonts,config}

# Copy binary
echo "Copying binary..."
cp "target/${TARGET}/release/LyMonS" "${BUILD_DIR}/bin/"
${STRIP_TOOL} "${BUILD_DIR}/bin/LyMonS" 2>/dev/null || echo "Strip failed (non-fatal)"

# Copy runtime assets and resources
echo "Copying runtime assets and resources..."
cp -fr assets/. "${BUILD_DIR}/assets/"
cp -fr data/.   "${BUILD_DIR}/data/"
cp -fr fonts/.  "${BUILD_DIR}/fonts/"

# Copy plugins
echo "Copying plugins..."
if ls target/${TARGET}/release/drivers/liblymons_driver_*.so 1>/dev/null 2>&1; then
    cp target/${TARGET}/release/drivers/liblymons_driver_*.so "${BUILD_DIR}/drivers/"
    ${STRIP_TOOL} "${BUILD_DIR}/drivers/"*.so 2>/dev/null || echo "Strip plugins failed (non-fatal)"
else
    echo "Warning: No plugin drivers found in target/${TARGET}/release/drivers/"
fi

# Bus discovery helper, shared with the Raspberry Pi and Orange Pi packages.
# It detects the board family and piCorePlayer at runtime and adjusts its
# advice accordingly, so one copy serves every deployment.
if [ ! -f scripts/show-buses.sh ]; then
    echo "Error: scripts/show-buses.sh not found (run this from the repo root)"
    exit 1
fi
cp scripts/show-buses.sh "${BUILD_DIR}/show-buses.sh"
chmod +x "${BUILD_DIR}/show-buses.sh"

# Config template. The driver folder path is set by install.sh at deploy time.
cat > "${BUILD_DIR}/config/lymons.yaml.example" <<'EOF'
# LyMonS Configuration
# Generated by install.sh. Review and edit before running.

display:
  folder: /DRIVER_DIR/      # set automatically by installer

  # Options: ssd1306, ssd1309, sh1106, sh1107, ssd1322, sh1122,
  #          st7789, st7796s, sharpmemory
  driver: ssd1309

  # Only needed for drivers offering more than one panel size (sh1107, st7789).
  # Single-size drivers ignore these. See the Supported Displays table in
  # README.md for the sizes each driver accepts.
  # width: 128
  # height: 64

  # --- I2C: ssd1306, ssd1309, sh1106, sh1107 --------------------------------
  bus:
    type: i2c
    bus: "/dev/i2c-1"       # Pi header I2C is bus 1
    address: 0x3C           # Common: 0x3C or 0x3D

  # --- SPI: any driver above, plus ssd1322, sh1122, st7789, st7796s and
  #          sharpmemory, which are SPI only ---------------------------------
  # Replace the i2c block above with this for a 4-wire SPI panel. On a Pi the
  # whole 40-pin header is one GPIO controller whose line offsets are the BCM
  # numbers, so dc_pin/rst_pin are BCM 24 and BCM 25 and gpio_chip can be left
  # unset. Enable SPI in the piCorePlayer web interface under Tweaks first.
  #
  # bus:
  #   type: spi
  #   bus: "/dev/spidev0.0"
  #   dc_pin: 24
  #   rst_pin: 25
  #   speed_hz: 8000000

  brightness: 128           # 0-255
  rotate_deg: 0             # 0, 90, 180, 270
  invert: false

# Location, used for sunrise/sunset and moon calculations
# Find your coordinates at https://www.latlong.net/
latitude: 42.36141
longitude: -71.10407

# Slim Server Connection (auto-detected if not specified)
# slimserver:
#   host: "localhost"
#   port: 9000

# Player MAC Address (auto-detected if not specified)
# player_mac: "aa:bb:cc:dd:ee:ff"
EOF

# Smart install.sh: detects environment, deploys to correct locations,
# generates gomonitor with correct paths baked in for this deployment
cat > "${BUILD_DIR}/install.sh" <<'INSTALLEOF'
#!/bin/sh
# LyMonS Universal Installer
# Detects piCorePlayer (TinyCore Linux) vs Debian/Raspberry Pi OS
# and deploys to the correct locations automatically.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "LyMonS Installer"
echo "================"

# Detect environment: check for pCP/TinyCore first, fall back to Debian/standard
detect_os() {
    # pCP: has pcp command, or /etc/issue mentions TinyCore/piCore
    if command -v pcp > /dev/null 2>&1 || \
       grep -qi "tinycore\|picore" /etc/issue 2>/dev/null; then
        echo "pcp"
        return
    fi
    # Debian / Raspberry Pi OS
    if grep -qi "debian\|raspbian\|ubuntu" /etc/os-release 2>/dev/null; then
        echo "linux"
        return
    fi
    # Unknown, so default to standard Linux behaviour
    echo "linux"
}

DEPLOY_MODE=$(detect_os)

if [ "${DEPLOY_MODE}" = "pcp" ]; then
    echo "Detected: piCorePlayer (TinyCore Linux)"
    RUNTIME_DIR="/mnt/mmcblk0p2/tce/lymons"
    BIN_DIR="${RUNTIME_DIR}"
    DRIVER_DIR="${RUNTIME_DIR}/drivers"
    CONFIG_DIR="${RUNTIME_DIR}/config"
else
    echo "Detected: Debian / Raspberry Pi OS"
    RUNTIME_DIR="${HOME}/lymons"
    BIN_DIR="/usr/local/bin"
    DRIVER_DIR="/usr/local/lib/lymons/drivers"
    CONFIG_DIR="${RUNTIME_DIR}/config"
fi

echo ""
echo "  Runtime : ${RUNTIME_DIR}"
echo "  Binary  : ${BIN_DIR}/LyMonS"
echo "  Drivers : ${DRIVER_DIR}"
echo "  Config  : ${CONFIG_DIR}/lymons.yaml"
echo ""

# Create directory structure
mkdir -p "${RUNTIME_DIR}/data" "${RUNTIME_DIR}/assets" "${RUNTIME_DIR}/fonts" \
         "${CONFIG_DIR}" "${DRIVER_DIR}"
[ "${DEPLOY_MODE}" = "linux" ] && mkdir -p "${BIN_DIR}"

# Deploy binary
cp "${SCRIPT_DIR}/bin/LyMonS" "${BIN_DIR}/LyMonS"
chmod +x "${BIN_DIR}/LyMonS"
echo "Installed binary: ${BIN_DIR}/LyMonS"

# Deploy drivers
if ls "${SCRIPT_DIR}/drivers/"*.so 1>/dev/null 2>&1; then
    cp "${SCRIPT_DIR}/drivers/"*.so "${DRIVER_DIR}/"
    echo "Installed drivers to ${DRIVER_DIR}/"
else
    echo "Warning: No driver plugins found in package"
fi

# Deploy runtime resources
cp -rf "${SCRIPT_DIR}/data/."   "${RUNTIME_DIR}/data/"
cp -rf "${SCRIPT_DIR}/assets/." "${RUNTIME_DIR}/assets/"
cp -rf "${SCRIPT_DIR}/fonts/."  "${RUNTIME_DIR}/fonts/"
cp -f  "${SCRIPT_DIR}/show-buses.sh" "${RUNTIME_DIR}/show-buses.sh"
chmod +x "${RUNTIME_DIR}/show-buses.sh"
echo "Installed runtime resources to ${RUNTIME_DIR}/"

# Deploy config: create from example if not already present, patch driver path
if [ ! -f "${CONFIG_DIR}/lymons.yaml" ]; then
    sed "s|folder: /DRIVER_DIR/|folder: ${DRIVER_DIR}/|" \
        "${SCRIPT_DIR}/config/lymons.yaml.example" > "${CONFIG_DIR}/lymons.yaml"
    echo "Created ${CONFIG_DIR}/lymons.yaml, please set your display driver and location"
else
    echo "Config exists, leaving ${CONFIG_DIR}/lymons.yaml unchanged"
fi

# Generate gomonitor with all paths resolved for this deployment
if [ "${DEPLOY_MODE}" = "pcp" ]; then
    cat > "${RUNTIME_DIR}/gomonitor" <<GOEOF
#!/bin/sh
# LyMonS for piCorePlayer - it's worth the squeeze
BINDIR="${RUNTIME_DIR}"

# Resolve player name from pCP config
PNAME=\$(grep "^NAME=" /usr/local/sbin/config.cfg 2>/dev/null | cut -d'"' -f2)

# Stop any running instance
killall LyMonS > /dev/null 2>&1; sleep 1
killall -9 LyMonS > /dev/null 2>&1

# Wait for squeezelite to be running before starting
echo "Waiting for squeezelite..."
until pidof squeezelite squeezelite-dsd > /dev/null 2>&1; do
    sleep 1
done
echo "Squeezelite running. Starting LyMonS${PNAME:+ for \${PNAME}}..."

# Ensure i2c is available
modprobe i2c_dev > /dev/null 2>&1
modprobe i2c-dev > /dev/null 2>&1

cd "\${BINDIR}"
exec sudo "\${BINDIR}/LyMonS" \
    \${PNAME:+--name "\${PNAME}"} \
    --config="${CONFIG_DIR}/lymons.yaml" \
    "\$@" > /dev/null 2>&1 &
GOEOF

else
    cat > "${RUNTIME_DIR}/gomonitor" <<GOEOF
#!/bin/sh
# LyMonS for Raspberry Pi - it's worth the squeeze
RUNTIME_DIR="${RUNTIME_DIR}"

# Stop any running instance
killall LyMonS > /dev/null 2>&1; sleep 1
killall -9 LyMonS > /dev/null 2>&1

# Wait for squeezelite (up to 30s), skip if not found
WAIT=0
while [ \$WAIT -lt 30 ]; do
    pidof squeezelite squeezelite-dsd > /dev/null 2>&1 && break
    sleep 1
    WAIT=\$((WAIT + 1))
done

cd "\${RUNTIME_DIR}"
exec sudo LyMonS \
    --config="${CONFIG_DIR}/lymons.yaml" \
    "\$@" > /dev/null 2>&1 &
GOEOF

fi
chmod +x "${RUNTIME_DIR}/gomonitor"
echo "Generated ${RUNTIME_DIR}/gomonitor"

# Platform-specific post-install
if [ "${DEPLOY_MODE}" = "pcp" ]; then
    # Load i2c tools extension
    tce-load -i i2c-tools.tcz 2>/dev/null || true
    # Register with pCP backup so it survives reboots
    if [ -f /usr/local/sbin/filetool.sh ]; then
        grep -v "^${RUNTIME_DIR}" /opt/.filetool.lst > /tmp/.filetool.lst.tmp \
            && mv /tmp/.filetool.lst.tmp /opt/.filetool.lst
        echo "${RUNTIME_DIR}" >> /opt/.filetool.lst
        pcp bu
        echo "Registered with piCorePlayer backup"
    fi
    echo ""
    echo "Installation complete!"
    echo ""
    echo "  Show buses  : ${RUNTIME_DIR}/show-buses.sh"
    echo "  Edit config : ${CONFIG_DIR}/lymons.yaml"
    echo "  Test        : ${RUNTIME_DIR}/gomonitor"
    echo "  Autostart   : add via piCorePlayer web interface > Tweaks > User Commands:"
    echo "                ${RUNTIME_DIR}/gomonitor &"
else
    echo ""
    echo "Installation complete!"
    echo ""
    echo "  Show buses  : ${RUNTIME_DIR}/show-buses.sh"
    echo "  Edit config : ${CONFIG_DIR}/lymons.yaml"
    echo "  Test        : ${RUNTIME_DIR}/gomonitor"
    echo "  Autostart   : add to /etc/rc.local before 'exit 0':"
    echo "                ${RUNTIME_DIR}/gomonitor &"
fi
INSTALLEOF
chmod +x "${BUILD_DIR}/install.sh"

# Package README
cat > "${BUILD_DIR}/README.md" <<EOF
# LyMonS ${VERSION} (${ARCH})

Dynamic OLED display driver for Logitech Media Server.

Works on **piCorePlayer (TinyCore Linux)** and **standard Raspberry Pi Linux**.
The installer detects your environment automatically.

## Installation

\`\`\`bash
tar xzf ${PACKAGE_NAME}.tgz
cd ${PACKAGE_NAME}
sudo ./install.sh
\`\`\`

That's it. The installer will:
- Detect piCorePlayer vs standard Linux
- Deploy the binary, drivers, and runtime assets to the correct locations
- Create a default configuration (edit before running)
- Generate a \`gomonitor\` launch script with paths pre-configured for your system
- On piCorePlayer: add to backup list and run \`pcp bu\` automatically

## Supported Displays

Color depth is a property of the driver, not the panel size.

| Driver        | Bus     | Color depth    | Panel sizes                                         |
|---------------|---------|----------------|-----------------------------------------------------|
| \`ssd1306\`     | I2C/SPI | Mono (1bpp)    | 128x64                                              |
| \`ssd1309\`     | I2C/SPI | Mono (1bpp)    | 128x64                                              |
| \`sh1106\`      | I2C/SPI | Mono (1bpp)    | 132x64                                              |
| \`sh1107\`      | I2C/SPI | Mono (1bpp)    | 128x128, 128x64                                     |
| \`ssd1322\`     | SPI     | Gray4 (4bpp)   | 256x64                                              |
| \`sh1122\`      | SPI     | Gray4 (4bpp)   | 256x64                                              |
| \`st7789\`      | SPI     | Rgb565 (16bpp) | 320x240, 320x170, 280x240, 240x240, 240x135, 160x80 |
| \`st7796s\`     | SPI     | Rgb565 (16bpp) | 480x320                                             |
| \`sharpmemory\` | SPI     | Mono (1bpp)    | 400x240                                             |

Set \`width\` and \`height\` in the \`display:\` block for the drivers that offer more
than one panel size. The rest fix their own size and ignore the values.

## Bus Interfaces

Enable the bus in the piCorePlayer web interface (Tweaks) and reboot, then run
the discovery helper to confirm the device nodes appeared:

\`\`\`bash
<install dir>/show-buses.sh
\`\`\`

It prints the I2C buses, SPI nodes and GPIO controllers the board exposes, the
line-numbering rule for the detected SoC, an \`i2cdetect\` scan of every bus and
any missing group membership.

- **I2C**: \`/dev/i2c-1\` on the 40-pin header, address usually 0x3C, sometimes 0x3D.
  The installer loads \`i2c-tools.tcz\` so \`i2cdetect -y 1\` is available to confirm
  the panel is answering.
- **SPI**: \`/dev/spidev0.0\` or \`/dev/spidev0.1\`, plus two GPIO lines for DC and
  reset. Pi header pins are BCM numbers, and the header GPIO controller is
  detected automatically, so \`gpio_chip\` is not needed on a Pi.

## piCorePlayer Autostart

Add via the piCorePlayer web interface (Tweaks → User Commands):
\`\`\`
/mnt/mmcblk0p2/tce/lymons/gomonitor &
\`\`\`

## Standard Pi Autostart

Add to \`/etc/rc.local\` before \`exit 0\`:
\`\`\`bash
\${HOME}/lymons/gomonitor &
\`\`\`

## License

GPL-3.0-or-later. Version ${VERSION} ($(date +%Y-%m-%d)). Built for: ${TARGET}
EOF

# Create package
cd /tmp
echo "Creating tarball..."
tar czf "${PACKAGE_NAME}.tgz" "${PACKAGE_NAME}/"
mv "${PACKAGE_NAME}.tgz" "${OLDPWD}/"

BINARY_SIZE=$(du -h "${BUILD_DIR}/bin/LyMonS" | cut -f1)
PACKAGE_SIZE=$(du -h "${OLDPWD}/${PACKAGE_NAME}.tgz" | cut -f1)

echo ""
echo "✓ Package created: ${PACKAGE_NAME}.tgz"
echo "  Binary:  ${BINARY_SIZE}"
echo "  Package: ${PACKAGE_SIZE}"
echo ""
echo "To deploy:"
echo "  tar xzf ${PACKAGE_NAME}.tgz && cd ${PACKAGE_NAME} && sudo ./install.sh"
