#!/bin/bash
# Create universal Raspberry Pi deployment package (.tgz)
# Single package works on piCorePlayer (TinyCore) and standard Raspberry Pi Linux
# install.sh detects the environment and deploys accordingly

set -e

TARGET="${1:-armv7-unknown-linux-gnueabihf}"
VERSION=$(grep '^version' Cargo.toml | head -1 | sed 's/.*"\(.*\)".*/\1/')
ARCH=$(echo "${TARGET}" | cut -d'-' -f1)
PACKAGE_NAME="lymons-${VERSION}-pcp-${ARCH}"
BUILD_DIR="/tmp/${PACKAGE_NAME}"

case "${TARGET}" in
    armv7-*)   STRIP_TOOL="arm-linux-gnueabihf-strip" ;;
    aarch64-*) STRIP_TOOL="aarch64-linux-gnu-strip" ;;
    *)         STRIP_TOOL="strip" ;;
esac

echo "Creating universal deployment package..."
echo "Version: ${VERSION}"
echo "Target:  ${TARGET}"
echo "Arch:    ${ARCH}"

# Verify cross-compiled binary exists
if [ ! -f "target/${TARGET}/release/LyMonS" ]; then
    echo "Error: Cross-compiled binary not found!"
    echo "Please run: ./scripts/cross-compile-pi.sh ${TARGET} first"
    exit 1
fi

# Clean and create flat build structure
rm -rf "${BUILD_DIR}"
mkdir -p "${BUILD_DIR}"/{bin,drivers,data,assets,fonts,config}

# Copy binary
echo "Copying binary..."
cp "target/${TARGET}/release/LyMonS" "${BUILD_DIR}/bin/"
${STRIP_TOOL} "${BUILD_DIR}/bin/LyMonS" 2>/dev/null || echo "Strip failed (non-fatal)"

# Copy runtime assets and resources
echo "Copying runtime assets and resources..."
cp -fr assets/. "${BUILD_DIR}/assets/"
cp -fr data/.   "${BUILD_DIR}/data/"
cp -fr fonts/.  "${BUILD_DIR}/fonts/"

# Copy plugins
echo "Copying plugins..."
if ls target/${TARGET}/release/drivers/liblymons_driver_*.so 1>/dev/null 2>&1; then
    cp target/${TARGET}/release/drivers/liblymons_driver_*.so "${BUILD_DIR}/drivers/"
    ${STRIP_TOOL} "${BUILD_DIR}/drivers/"*.so 2>/dev/null || echo "Strip plugins failed (non-fatal)"
else
    echo "Warning: No plugin drivers found in target/${TARGET}/release/drivers/"
fi

# Config template — driver folder path is set by install.sh at deploy time
cat > "${BUILD_DIR}/config/lymons.yaml.example" <<'EOF'
# LyMonS Configuration
# Generated by install.sh — review and edit before running

display:
  folder: /DRIVER_DIR/      # set automatically by installer
  driver: ssd1309           # Options: ssd1306, ssd1309, sh1106, ssd1322
  bus:
    type: i2c
    bus: "/dev/i2c-1"
    address: 0x3C           # Common: 0x3C or 0x3D
  brightness: 128           # 0-255
  rotate_deg: 0             # 0, 90, 180, 270
  invert: false

# Location — used for sunrise/sunset and moon calculations
# Find your coordinates at https://www.latlong.net/
latitude: 42.36141
longitude: -71.10407

# Slim Server Connection (auto-detected if not specified)
# slimserver:
#   host: "localhost"
#   port: 9000

# Player MAC Address (auto-detected if not specified)
# player_mac: "aa:bb:cc:dd:ee:ff"
EOF

# Smart install.sh — detects environment, deploys to correct locations,
# generates gomonitor with correct paths for the deployment
cat > "${BUILD_DIR}/install.sh" <<'INSTALLEOF'
#!/bin/sh
# LyMonS Universal Installer
# Detects piCorePlayer (TinyCore Linux) vs standard Raspberry Pi Linux
# and deploys accordingly.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "LyMonS Installer"
echo "================"

# Detect environment
if grep -qi "tinycore" /etc/issue 2>/dev/null; then
    echo "Detected: piCorePlayer (TinyCore Linux)"
    DEPLOY_MODE="pcp"
    RUNTIME_DIR="/mnt/mmcblk0p2/tce/lymons"
    BIN_DIR="${RUNTIME_DIR}"
    DRIVER_DIR="${RUNTIME_DIR}/drivers"
    CONFIG_DIR="${RUNTIME_DIR}/config"
else
    echo "Detected: Standard Linux (Raspberry Pi OS)"
    DEPLOY_MODE="linux"
    RUNTIME_DIR="${HOME}/lymons"
    BIN_DIR="/usr/local/bin"
    DRIVER_DIR="/usr/local/lib/lymons/drivers"
    CONFIG_DIR="${RUNTIME_DIR}/config"
fi

echo ""
echo "  Runtime : ${RUNTIME_DIR}"
echo "  Binary  : ${BIN_DIR}/LyMonS"
echo "  Drivers : ${DRIVER_DIR}"
echo "  Config  : ${CONFIG_DIR}/lymons.yaml"
echo ""

# Create directories
mkdir -p "${RUNTIME_DIR}/data" "${RUNTIME_DIR}/assets" "${RUNTIME_DIR}/fonts" \
         "${CONFIG_DIR}" "${DRIVER_DIR}"
[ "${DEPLOY_MODE}" = "linux" ] && mkdir -p "${BIN_DIR}"

# Copy binary
cp -v "${SCRIPT_DIR}/bin/LyMonS" "${BIN_DIR}/"
chmod +x "${BIN_DIR}/LyMonS"

# Copy drivers
if ls "${SCRIPT_DIR}/drivers/"*.so 1>/dev/null 2>&1; then
    cp -v "${SCRIPT_DIR}/drivers/"*.so "${DRIVER_DIR}/"
else
    echo "Warning: No driver plugins found in package"
fi

# Copy runtime resources
cp -rfv "${SCRIPT_DIR}/data/."   "${RUNTIME_DIR}/data/"
cp -rfv "${SCRIPT_DIR}/assets/." "${RUNTIME_DIR}/assets/"
cp -rfv "${SCRIPT_DIR}/fonts/."  "${RUNTIME_DIR}/fonts/"

# Config — create from example if not already present, patch driver path
if [ ! -f "${CONFIG_DIR}/lymons.yaml" ]; then
    sed "s|folder: /DRIVER_DIR/|folder: ${DRIVER_DIR}/|" \
        "${SCRIPT_DIR}/config/lymons.yaml.example" > "${CONFIG_DIR}/lymons.yaml"
    echo "Created ${CONFIG_DIR}/lymons.yaml"
    echo "Please review and edit with your display driver and location settings"
fi

# Generate gomonitor with paths baked in for this deployment
if [ "${DEPLOY_MODE}" = "pcp" ]; then
    cat > "${RUNTIME_DIR}/gomonitor" <<EOF
#!/bin/sh
# LyMonS for piCorePlayer - it's worth the squeeze
echo "LyMonS for piCorePlayer - it's worth the squeeze"
BINDIR="${RUNTIME_DIR}"
PNAME=\$(grep "^NAME=" /usr/local/sbin/config.cfg | cut -d'"' -f2)

sudo killall LyMonS > /dev/null 2>&1
sudo killall LyMonS > /dev/null 2>&1
sudo killall LyMonS > /dev/null 2>&1

until pids=\$(pidof squeezelite squeezelite-dsd); do
  echo "Waiting for squeezelite ..."
  sleep 1
done
echo "Starting LyMonS. Player: \${PNAME}"

VIZ=""
if [ \$# -gt 0 ]; then
  VIZ="-a \"\${1:-NA}\" "
fi

sudo modprobe i2c_dev > /dev/null 2>&1
sudo modprobe i2c-dev > /dev/null 2>&1
cd "\${BINDIR}"
CMD="sudo \${BINDIR}/LyMonS --name \"\${PNAME}\" --config=${CONFIG_DIR}/lymons.yaml \${VIZ} \$2 \$3 \$4 \$5 \$6 \$7 \$8 \$9"
echo \$CMD
eval \$CMD > /dev/null &
exit
EOF
else
    cat > "${RUNTIME_DIR}/gomonitor" <<EOF
#!/bin/sh
# LyMonS for Raspberry Pi - it's worth the squeeze
RUNTIME_DIR="${RUNTIME_DIR}"

sudo killall LyMonS > /dev/null 2>&1
sudo killall LyMonS > /dev/null 2>&1

sudo modprobe i2c_dev > /dev/null 2>&1
sudo modprobe i2c-dev > /dev/null 2>&1
cd "\${RUNTIME_DIR}"
CMD="sudo LyMonS --config=${CONFIG_DIR}/lymons.yaml \$@"
echo \$CMD
eval \$CMD > /dev/null &
exit
EOF
fi
chmod +x "${RUNTIME_DIR}/gomonitor"

# Platform-specific post-install steps
if [ "${DEPLOY_MODE}" = "pcp" ]; then
    tce-load -i i2c-tools.tcz 2>/dev/null || true
    if [ -f /usr/local/sbin/filetool.sh ]; then
        grep -v "^${RUNTIME_DIR}" /opt/.filetool.lst > /tmp/.filetool.lst.tmp \
            && mv /tmp/.filetool.lst.tmp /opt/.filetool.lst
        echo "${RUNTIME_DIR}" >> /opt/.filetool.lst
        echo "Added ${RUNTIME_DIR} to piCorePlayer backup list"
        pcp bu
        echo "Backup completed"
    fi
    echo ""
    echo "Installation complete!"
    echo ""
    echo "Next steps:"
    echo "  1. Edit ${CONFIG_DIR}/lymons.yaml — set your display driver and location"
    echo "  2. Test:      ${RUNTIME_DIR}/gomonitor"
    echo "  3. Autostart: add the following via the piCorePlayer web interface:"
    echo "                ${RUNTIME_DIR}/gomonitor &"
else
    echo ""
    echo "Installation complete!"
    echo ""
    echo "Next steps:"
    echo "  1. Edit ${CONFIG_DIR}/lymons.yaml — set your display driver and location"
    echo "  2. Test:      ${RUNTIME_DIR}/gomonitor"
    echo "  3. Autostart: add '${RUNTIME_DIR}/gomonitor &' to /etc/rc.local"
fi
INSTALLEOF
chmod +x "${BUILD_DIR}/install.sh"

# Package README
cat > "${BUILD_DIR}/README.md" <<EOF
# LyMonS ${VERSION} (${ARCH})

Dynamic OLED display driver for Logitech Media Server.

Works on **piCorePlayer (TinyCore Linux)** and **standard Raspberry Pi Linux**.
The installer detects your environment automatically.

## Installation

\`\`\`bash
tar xzf ${PACKAGE_NAME}.tgz
cd ${PACKAGE_NAME}
sudo ./install.sh
\`\`\`

That's it. The installer will:
- Detect piCorePlayer vs standard Linux
- Deploy the binary, drivers, and runtime assets to the correct locations
- Create a default configuration (edit before running)
- Generate a \`gomonitor\` launch script with paths pre-configured for your system
- On piCorePlayer: add to backup list and run \`pcp bu\` automatically

## Supported Displays

| Driver   | Resolution | Interface |
|----------|-----------|-----------|
| SSD1306  | 128×64    | I2C       |
| SSD1309  | 128×64    | I2C       |
| SH1106   | 132×64    | I2C       |
| SSD1322  | 256×64    | SPI       |

## piCorePlayer Autostart

Add via the piCorePlayer web interface (Tweaks → User Commands):
\`\`\`
/mnt/mmcblk0p2/tce/lymons/gomonitor &
\`\`\`

## Standard Pi Autostart

Add to \`/etc/rc.local\` before \`exit 0\`:
\`\`\`bash
\${HOME}/lymons/gomonitor &
\`\`\`

## License

GPL-3.0-or-later — Version ${VERSION} ($(date +%Y-%m-%d)) — Built for: ${TARGET}
EOF

# Create package
cd /tmp
echo "Creating tarball..."
tar czf "${PACKAGE_NAME}.tgz" "${PACKAGE_NAME}/"
mv "${PACKAGE_NAME}.tgz" "${OLDPWD}/"

BINARY_SIZE=$(du -h "${BUILD_DIR}/bin/LyMonS" | cut -f1)
PACKAGE_SIZE=$(du -h "${OLDPWD}/${PACKAGE_NAME}.tgz" | cut -f1)

echo ""
echo "✓ Package created: ${PACKAGE_NAME}.tgz"
echo "  Binary:  ${BINARY_SIZE}"
echo "  Package: ${PACKAGE_SIZE}"
echo ""
echo "To deploy:"
echo "  tar xzf ${PACKAGE_NAME}.tgz && cd ${PACKAGE_NAME} && sudo ./install.sh"
